#!/bin/bash
####################################################
# This script is automatically generated by the GUI.

export exps="/home/pharting/Desktop/Aghion_follow_up/exp2509_USED/Robustness/speed_tech_progress/test_007 /home/pharting/Desktop/Aghion_follow_up/exp2509_USED/Robustness/speed_tech_progress/test /home/pharting/Desktop/Aghion_follow_up/exp2509_USED/Robustness/speed_tech_progress/test_005  "


for exp in $exps; do

	 cd $exp 
	 cp $exp'/variables.txt' /home/pharting/Desktop/GUI_EVA2/src/Data_Analysis_GUI_Serial/Data_Files/variables.txt
	 cp $exp'/time_series_data.txt' /home/pharting/Desktop/GUI_EVA2/src/Data_Analysis_GUI_Serial/Data_Files/time_series_data.txt
	 cp $exp'/multiple_time_series_data.txt' /home/pharting/Desktop/GUI_EVA2/src/Data_Analysis_GUI_Serial/Data_Files/multiple_time_series_data.txt
	 cp $exp'/growth_rate_data.txt' /home/pharting/Desktop/GUI_EVA2/src/Data_Analysis_GUI_Serial/Data_Files/growth_rate_data.txt
	 cp $exp'/ratio_data.txt' /home/pharting/Desktop/GUI_EVA2/src/Data_Analysis_GUI_Serial/Data_Files/ratio_data.txt
	 cp $exp'/boxplot_data.txt' /home/pharting/Desktop/GUI_EVA2/src/Data_Analysis_GUI_Serial/Data_Files/boxplot_data.txt
	 cp $exp'/histogram_data.txt' /home/pharting/Desktop/GUI_EVA2/src/Data_Analysis_GUI_Serial/Data_Files/histogram_data.txt
	 cp $exp'/heat_maps_data.txt' /home/pharting/Desktop/GUI_EVA2/src/Data_Analysis_GUI_Serial/Data_Files/heat_maps_data.txt
	 cp $exp'/scatter_data.txt' /home/pharting/Desktop/GUI_EVA2/src/Data_Analysis_GUI_Serial/Data_Files/scatter_data.txt
	 cp $exp'/Configure.r' /home/pharting/Desktop/GUI_EVA2/src/Data_Analysis_GUI_Serial/Configure.r
 

	 bash run_exp.sh 
	 echo '$EXPERIMENT_NAME=' $exp 
	 cd .. 
done

echo '  Done.'
