#!/bin/bash
####################################################
# This script is automatically generated by the GUI./ replaced using updater class
# It contains the setting of the current working directory and launching of the run_exp.sh
###################################################


cd <SimulationSettings.WORKING_DIRECTORY>
bash run_exp.sh


