#!/bin/bash
####################################################
# This script is automatically generated by the GUI.
# It contains the parameter settings for an experiment 
###################################################


<ExperimentSettings>