#!/bin/bash
####################################################
# This script is automatically generated by the GUI.
# It contains the setting of the current working directory and launching of the run_exp.sh
###################################################


cd /home/pharting/Desktop/GUISVN/Exp3
bash run_exp.sh


